"""changing  product price from int to float (:

Revision ID: 2265087ef384
Revises: d69504fa2e85
Create Date: 2026-08-27 15:01:27.165092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2265087ef384'
down_revision: Union[str, Sequence[str], None] = 'd69504fa2e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
