"""changin cart

Revision ID: 4766ce5f8c22
Revises: 59b7663af178
Create Date: 2026-09-02 15:11:52.590299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4766ce5f8c22'
down_revision: Union[str, Sequence[str], None] = '59b7663af178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_user_product'), 'cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_user_product'), 'cart', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
