"""adding pledge shares in product model

Revision ID: 59b7663af178
Revises: 0c0cae7bf760
Create Date: 2026-08-31 15:14:31.719370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b7663af178'
down_revision: Union[str, Sequence[str], None] = '0c0cae7bf760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pledge_shares', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pledge_shares')
    # ### end Alembic commands ###
