"""adding cash column to users

Revision ID: 75fcb68bfaaa
Revises: 2265087ef384
Create Date: 2026-08-27 21:44:03.631841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fcb68bfaaa'
down_revision: Union[str, Sequence[str], None] = '2265087ef384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###
